### ISSUE TITLE
Mouse weirdness

### ISSUE THREAD

**Issue by TheOneWhoAfksInTDS** [GMH-Code/Quake-WASM#2]
Recently, I have encountered an EXTREMELY common bug that causes locking the mouse to disable the ability to turn. I experienced this on a chromebook model 3100. If you are able to fix it, I would appreciate it. Thanks!

**Comment by GMH-Code** [comment]
Hi @TheOneWhoAfksInTDS

I've taken a look at the code and have an idea of what the problem is.  I don't have a Chromebook though, so I'm going to try to find a different way of reliably reproducing it.

I have a feeling this is some leftover old desktop SDL1 code which I didn't remove or filter out.  There is a check made to see if the pointer has moved from the centre position (where it naturally 'sits' on desktop systems), which might conflict with screen scaling or overlays.

**Comment by GMH-Code** [comment]
Okay, I believe it's fixed.

The problem actually appears to be with Emscripten and SDL2 handling custom templates, so I've had to write a workaround.

In case the technical reason matters: If the mouse is set to 'relative' mode whilst the canvas is invisible (part of the custom template), then the relative co-ordinates can sometimes, but not always, be 0, 0 for the duration that the mouse is captured.  Occasionally refreshing the page works, but even interacting with the JavaScript or SDL2 at runtime (through test shortcut keys) didn't solve it.   Even if you reset to absolute mode and back to relative, the problem persists.  SDL2 even reports relative mode is working when it isn't ever reporting proper co-ordinates.

The workaround appears to be to delay the initial switch, effectively until after the canvas is shown and everything is ready.

Anyway, can you check the version using the link from the main README.md page and see if it now works okay for you?  Please give it a few goes and check it's not got erratic behaviour.

If you're convinced the problem is fixed, I'll publish the source change.

**Comment by GMH-Code** [comment]
Just a note -- you may have to reset your browser data for the domain, or try it in Private Browsing / Incognito mode.  I have a one-day cache on the static files at the moment.

**Comment by TheOneWhoAfksInTDS** [comment]
It worked! Thanks!
