### ISSUE TITLE
WebSocket multiplayer

### ISSUE THREAD

**Issue by initialed85** [GMH-Code/Quake-WASM#8]
Hi mate,

I managed to get WebSocket multiplayer working (I ended up implementing a new `net_landriver_t` because I couldn't get the magic Emscripten BSD-to-WebSocket thing working (but thats not to say it shouldn't be possible, I was learning a bunch of stuff about the Quake network protocol at the same time).

The code is [here](https://github.com/initialed85/Quake-WASM) but I'm not a C programmer by any stretch- plus its a bit messy, I had to make a special [WebSocket to UDP proxy](https://github.com/initialed85/quake-websocket-proxy) and then I had to make some tweaks to the Quake dedicated server [here](https://github.com/initialed85/Quake-LinuxUpdate) because out of the box it assumes that all connections from the same IP (but a different port) are essentially the same player trying to reconnect (which didn't really blend well with running the proxy next to the Quake server as containers, where you get multiple "players" connecting from the same IP).

Anyway- it's sort of workable but its a bit messy; do you want a PR back in to this repo to kick the tyres on or anything?

**Comment by GMH-Code** [comment]
Hi,

This is great work -- well done!  I am really tempted to ask for a pull request, but I need to think about it for a while -- mainly to see if there is enough interest.

I wouldn't really change anything, but thoughts I had on what to do next:

- I like the server-side method of proxying WebSockets to a regular Quake server – this has the potential to allow regular Quake clients to join the same games as Quake-WASM, assuming the protocol implementation hasn’t been altered on the server end and we’re still allowing regular clients to connect.

- I knew about details of the Quake protocol (mainly from Q2, even before the source was released) but to my surprise I wasn't aware of the inability to have multiple clients on one IP until now.  That obviously breaks simultaneous NAT connections.  I guess that wasn't really a thing back then.

- On first read, `net_websocket.c` and `net_websocket.h` look like a good conversion of the UDP version combined with Emscripten's WebSocket support.  I wouldn’t alter much of it at all.

- I would add several more features to the networking module and perhaps change some minor things, but I’d only do this on top of a PR, since your code already looks good.

- Networking/protocol exploits/bugs elsewhere in the code are a problem even if they are limited to the client’s WASM runtime.  We don’t want vulnerabilities being exploited in any way, even if the result is limited to crashes, glitches, people being kicked, cheating, or other issues.

- I'm unsure of whether QuakeWorld’s networking code is more suitable when compared to regular Quake.  The Internet seems split on that.  Things like missing client prediction/lag compensation aren't such a big deal nowadays, but that also means that people will have to host servers close by, which limits our scope.  Personally, I am used to the dialup modem days (180ms ping and tweaking settings so the transmit buffers don’t fill up -- arrgh).  I can imagine people will complain about delays between pressing a key and moving.

- You have hardcoded IP addresses and ports.  I'm sure you are fully aware of that.

- I prefer not to use `-sASYNCIFY` at all, but I can see why you’ve used it.  It doesn’t seem to have affected the benchmarks noticeably – this is likely to be because I opted to control the main event loop, otherwise I expect it’d come at the price of 10-20% speed.  If possible, scope should be manually limited so the linking process only instruments parts of the code necessary to solve the problem.  Asyncifying the entire application and using sleeps to return control to the browser without popping out of the stack entirely is almost always the easiest way to get around blocking code, but then (if I remember rightly) every function along the stack must also be instrumented wherever sleeps are used, unless inlined by compiler optimisation.  SDL2 also contains internal sleeps when building in Emscripten, but those are often unnecessary and can be turned off.

- Don't forget to turn off debug flags for production builds!

- You've lifted the EDICT limit, which is fine, but it'd be helpful to say why -- such as which mods or maps hit the limit.  Other engines have lifted limits -- some of which I don't agree with because some of the caps can actually benefit performance on older systems, especially in WASM.  Lifting limits can be done to match what other engines offer, but as I expect you know, they aren't part of the heap, and doing so increases overall browser RAM usage for each limit lifted.  I considered lifting the EDICT count and many other limits too (or making them dynamically scale in blocks), but didn't because I was a way off hitting them, and the ultimate goal was simply to make the game work as it did before.  Since it only looked like modern maps and some mods needed the limits lifted, I didn't do so.

- I see you’ve used another project to host the server, but I see no reason why Quake-WASM can’t handle hosting if it’s secure.  I should probably make the regular Linux Quake build easier too, but again I'm a little concerned if someone hosts publically it due to potentially dangerous server-side exploits.  I’m also a bit concerned about other projects having similar issues!
 
- I am wondering whether the retro gaming community wants this enough and will give us enough support(?)

Overall, I want to add it because network support isn't there right now, and I can see so much I want to do with it, but I need a bit of convincing from the community that it's going to be popular enough!

Other input from anyone would be welcome.
