### ISSUE TITLE
Escape key not available on some devices

### ISSUE THREAD

**Issue by idoblenderstuffs** [GMH-Code/Quake-WASM#9]
This web port is decently playable using my iPad with the keyboard case accessory, apart from the lack of an escape key. I don't know why Apple would make such a decision, but it makes exiting any menus in this port impossible, and means that I can't change any settings, making the game largely awkward to play. Some way to rebind the main keys before loading the game would be useful to fix this, or just providing some other keybind that does an escape.

**Comment by GMH-Code** [comment]
This can be done in any one of the following ways:

1. Try `CMD` + `.` (I presume you have tried this).
2. Or, boot the game with the following URL parameters to make the usually unused `N` key go to the main menu: https://quake.m-h.org.uk/?+bind&n&menu_main
3. If you don't want to modify the URL like this, boot the game, then immediately (before you start or resume playing) go to `Options` > `Go to Console` (no ESC key needed).  Type `bind n menu_main` then `quit` to save your choice to the browser database.

I will probably modify the default binds so this is a default, but there you go.

**Comment by GMH-Code** [comment]
I'll leave this open until you say whether any of those worked!

**Comment by GMH-Code** [comment]
Apologies, please disregard the comment I previously made here.  I will post an update shortly.

**Comment by GMH-Code** [comment]
I've had a quick look for you.

It is possible to bind keys to *open* menus (main or otherwise), but, like you have said, it is not currently possible to close them nor go up a level if you're missing the `Esc` key.  The game has many hardcoded uses of `K_ESCAPE` (basically ASCII code 27), so it'd mean adding to those.  Easy enough to do, but I have to be a little careful doing that as it may conflict with bindable keys, which `Esc` is not.  I didn't ever imagine that key would be missing!

What I can suggest is:

1. Try `CMD` + `.` (dot) on your iPad to go up a level or exit the menu -- I expect you've already tried this, but let me know if it works anyway.
2. If that key combination doesn't work, maybe it is possible to map an alternative key on the iPad (definitely not ideal).
3. You could use the console to set binds for functionality you want, but this still won't allow you to `Esc` out of menus if you open one and choose to bail out.
4. You can also set binds on the start of the game, e.g. https://quake.m-h.org.uk/?+bind&n&menu_main , but again this won't allow you to exit the menus with Esc.

**Comment by GMH-Code** [comment]
I'll close this now, but feel free to comment if there is still a problem!
